FROM python:3.8-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY . .

# Set environment variables
ARG DB_HOSTNAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_NAME

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY

ARG PAYPAL_CLIENT_ID
ARG PAYPAL_CLIENT_SECRET

ARG SECURITY_PASSWORD_SALT
ARG EMAIL_USER
ARG EMAIL_PASSWORD

ENV DB_HOSTNAME=$DB_HOSTNAME
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_PORT=$DB_PORT

ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ENV PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
ENV PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET

ENV SECURITY_PASSWORD_SALT=$SECURITY_PASSWORD_SALT
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD

# Run the app
CMD [ "python", "./run.py" ]

EXPOSE 5000