name: CI/CD Pipeline to deploy TSY-IABS Backend Application to AWS Elastic Beanstalk

on:
  push:
    branches:
      - sprint4/booking_staff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t tsy-iabs-be .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag tsy-iabs-be:latest ${{ secrets.DOCKERHUB_USERNAME }}/tsy-iabs-be:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/tsy-iabs-be:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to AWS Elastic Beanstalk
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Elastic Beanstalk Deploy
      run: |
        eb init -p docker tsy-iabs-be --region ${{ secrets.AWS_REGION }}
        eb use tsy-iabs-env
        eb deploy
