name: CI/CD Pipeline to deploy TSY-IABS Backend Application to AWS Elastic Beanstalk

on:
  push:
    branches:
      - sprint4/booking_staff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t tsy-iabs-be .

    - name: Log in to Docker Hub
      # run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Push Docker image to Docker Hub
      run: |
        docker tag tsy-iabs-be:latest ${{ secrets.DOCKERHUB_USERNAME }}/tsy-iabs-be:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/tsy-iabs-be:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awsebcli

    # Deploy to existing AWS Elastic Beanstalk environment, called tsy-iabs-env
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v15
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: tsy-iabs
        environment_name: tsy-iabs-env
        version_label: ${{ github.sha }}
        region: ap-southeast-1
        deployment_package: ${{ secrets.DOCKERHUB_USERNAME }}/tsy-iabs-be:latest
